name: date_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  go_router: ^14.8.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  io: ^1.0.5
  google_fonts: ^6.2.1
  flutter_localization: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    #Icons

    #images
    - lib/assets/l10n/
    - lib/assets/images/
    - lib/assets/images/base/logo_icon.png
    - lib/assets/images/login/
    - lib/assets/images/login/login_background_image.png
    - lib/assets/icons/
    - lib/assets/icons/auth/
    - lib/assets/icons/auth/apple_icon.png
    - lib/assets/icons/auth/facebook_icon.png


    #fonts
fonts:
  - family: Inter
    fonts:
      - asset: lib/assets/fonts/Poppins/Poppins-Black.ttf
      - asset: lib/assets/fonts/Poppins/Poppins-Bold.ttf
      - asset: lib/assets/fonts/Poppins/Poppins-ExtraBold.ttf
      - asset: lib/assets/fonts/Poppins/Poppins-Light.ttf
      - asset: lib/assets/fonts/Poppins/Poppins-Medium.ttf
      - asset: lib/assets/fonts/Poppins/Poppins-Regular.ttf
      - asset: lib/assets/fonts/Poppins/Poppins-SemiBold.ttf
